version: '3.8'
services:
  bookmarker-api:
    build:
      context: bookmarker-api
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarker-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - bookmarker-db
  bookmark-gui:
    build:
      context: bookmark-gui
      dockerfile: Dockerfile-gui.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      BOOKMARK_API_URI: http://bookmarker-api:8080
    ports:
      - "10443:10443"
    restart: always
    depends_on:
      - bookmarker-api