apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarker-api
  labels:
    app: bookmarker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarker-api
  strategy: {}
  template:
    metadata:
      labels:
        app: bookmarker-api
    spec:
      containers:
      - image: manjosh1990/bookmarker-api-jib
        name: bookmarker-api-jib